spring.application.name=springboot-restfull-mircoservice

spring.datasource.url=jdbc:mysql://localhost:3306/user_management
spring.datasource.username=root
spring.datasource.password=Abhishek@1

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


# Enable Actuator features
# this will enable all Actuator properties
management.endpoints.web.exposure.include=*

# All info for this project
info.app.name=Spring Boot Restful Web Services
info.app.description=Spring Boot Restful Web Services
info.app.version=1.0.0

# This will enable the above info for the project
management.info.env.enabled=true

# This will show all properties of health
management.endpoint.health.show-details=always

# This is used to enable the Shutdown feature for Service
management.endpoint.shutdown.enabled=true